
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
        
